### DISCUSSION TITLE
All About Anything as a platform

### DISCUSSION THREAD

**Discussion by hawkrives** [StoDevX/AAO-React-Native#6937] [Ideas]
I think I do like the model of having AAO/AAA as a "platform" app. 

Each "app listed on the store" gets an autogenerated Xcode project, and both xcproj and runtime app are configured by a file in the repo - every module for every college is in the platform, and configured by that json file into the appropriate tab / stack combo

… kinda like what I scribbled a few days ago with the json app config thing. *idea heavily inspired by expo's EAS config thing. 

<details><summary>A summary of how different screens should expose filters/search/grouping/sorting options</summary>

```yaml
%YAML 1.2
---
menuItems:
  - more:
    - group by
    - sort by
    - reset(?)
---
module: menu

group:
  - key: category
    label: Category
  - key: title
    pipe: firstLetter
    label: Title

sort:
  - key: title
    label: Title

search:
  - key: title
  - key: description

facetMode: suggestion | toolbar

facet:
  - key: isSpecial
    label: Specials
    type: toggle

  - key: station
    label: Stations
    type: select-one
    auto: true

  - key: dietary-restriction
    label: Dietary Restriction
    type: select-many
    mode: all
    options:
      - value: vegan
        label: Vegan
        detail: Contains no meat, fish, …
        image: {href: https://…, tint:}

timeTravel:
  enabled: true
  window:
    from: yesterday
    until: tomorrow
---
module: calendar

group:
  - key: category
    label: Category
  - key: firstLetter
    label: Title

sort:
  - keys: [date]
    label: Date

search:
  - key: title
  - key: description

facet:
  - key: isFeatured
    label: Featured
    type: toggle

  - key: category
    label: Categories
    type: select-one
    auto: true

  - key: source
    label: Calendar
    type: select-many
    mode: any
    auto: true
---
module: jobs

group:
  - key: office
    label: Office
  - key: hours
    label: Hours
  - key: period
    label: Time Period
  - key: category
    label: Category

sort:
  - keys: [date, a, b]
    label: Date

search:
  - key: title
  - key: description

facet:
  - key: category
    label: Categories
    type: select-one
    auto: true

  - key: office
    label: Office
    type: select-one
    auto: true

  - key: period
    label: Time Period
    type: select-one
    auto: true

  - key: hours
    label: Hours
    type: select-one
    auto: true
---
module: hours

group:
  - key: category
    label: Category
  - key: status
    label: Status

sort:
  - keys: [sort]
    label: Default
  - keys: [title]
    label: Title
  - keys: [status]
    label: Status

search:
  - key: title

facet:
  - key: is-open
    type: toggle
    label: Open Now
  - key: category

timeTravel:
  enabled: true
  window:
    from: 1 month before now
    until: 1 month from now
---
module: directory

group:
  - key: lastInitial
    label: Last Initial
  - key: firstInitial
    label: First Initial
  - key: department
    label: Department
  - key: major
  - key: building

sort:
  - lastName, firstName
  - firstName, lastName
  - department
  - building, lastName

search:
  - displayName
  - location = building . " " . room
  - phone
  - email
  - title
  - department

facet:
  - key: department, major, building

---
module: news

group:
  - date
  - category
  - author

sort:
  - date
  - title
  - author

search:
  - title
  - content
  - category

facet:
  - category
  - featured
---
module: contacts
comment: put into directory?
---
module: streams(?)
comment: merge with calendar?
---
module: other-modes

group:
  - mode

search:
  - title
  - description
  - url?

sort:
  - title

facet: []
---
module: dictionary

group:
  - first-letter
search: [term, definition]
sort: 
  - term
facet: []
---
module: orgs

group:
  - name|first-letter
  - category

sort:
  - name
  - category, name

search:
  - name
  - description

facet:
  - category
  - meeting days(?)
---
module: a-z
---
module: stoprint-jobs

group: [name, dateQueued]
sort: [name, dateQueued]
search: [name]
facet: []
---
module: course-catalog

group:
  - space-available
  - term
  - gened
  - department
  - level
  - is-open

sort:
  - department, number, section
  - title

search:
  - title
  - description
---
``` 

</details>

<details><summary>App config as JSON</summary>

```json
{
  "app": {
    "name": "All About Olaf",
    "tint": "fancy(colors go here)",
    "layout": "features"
  },
  "layouts": [
    {
      "id": "features",
      "mode": "features",
      "layout": [
        {
          "heading": "Menus"
        },
        {
          "title": "Stav Hall",
          "size": "¼",
          "view": "Menus",
          "source": {
            "uri": "https://stolaf.api.frogpond.tech/v1/food/menus/named/stav-hall",
            "cache-for": "1 hour"
          },
          "sort": [
            "title"
          ],
          "group": [
            "station",
            "isSpecial",
            "dietaryRestriction"
          ],
          "search": [
            "title",
            "description"
          ],
          "facetMode": "toolbar",
          "facets": [

          ]
        }
      ]
    },
    {
      "id": "tabbed",
      "mode": "tabs",
      "tabs": [

      ]
    }
  ]
}
``` 

</details>
