### ISSUE TITLE
Report Hours screen doesn't actually submit anything

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1189]
I'm envisioning it directly submitting a PR to our repo, by way of a github token embedded in the app.

To do this, we'll need to be able to format YAML in a way that we like from a data structure, and we'll need to hook up the PRing bit too.

**Comment by elijahverdoorn** [comment]
I still think that we should run a backend server for this stuff instead of directing things to Github, but if something was built to direct this information to GitHub, it would be better than nothing.

**Comment by hawkrives** [comment]
I still don’t see what a server gets us over static files in github. We’d still need to verify submissions before accepting them, which PRs give us for free. We’d have to _host_ the server and maintain uptime, which github gives us for free. 

What else is there?

Kinda a moot point, since I haven’t built the PRing function yet, but I’m curious.

**Comment by hawkrives** [comment]
<details><summary>data</summary>

```json
{
      "name": "Stav Hall",
      "image": "stav",
      "category": "Food",
      "schedule": [
        {
          "title": "Breakfast",
          "hours": [
            {
              "days": [
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
              ],
              "from": "7:00am",
              "to": "9:45am"
            },
            {
              "days": [
                "Su"
              ],
              "from": "8:30am",
              "to": "10:15am"
            }
          ]
        },
        {
          "title": "Lunch",
          "hours": [
            {
              "days": [
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr"
              ],
              "from": "10:30am",
              "to": "2:00pm"
            },
            {
              "days": [
                "Sa",
                "Su"
              ],
              "from": "11:00am",
              "to": "1:30pm"
            }
          ]
        },
        {
          "title": "Dinner",
          "hours": [
            {
              "days": [
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa",
                "Su"
              ],
              "from": "4:30pm",
              "to": "7:30pm"
            }
          ]
        }
      ],
      "breakSchedule": {
        "fall": [],
        "thanksgiving": [],
        "winter": [],
        "interim": [],
        "spring": [],
        "easter": [],
        "summer": []
      }
    }
```

</details>

```js
stringified = jsYaml.safeDump(data, {flowLevel: 4})
    .split('\n')
    .map(l => ['schedule:', 'breakSchedule:'].includes(l) ? `\n${l}` : l)
    .join('\n')
```

```yaml
# stringified
name: Stav Hall
image: stav
category: Food

schedule:
  - title: Breakfast
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Sa], from: '7:00am', to: '9:45am'}
      - {days: [Su], from: '8:30am', to: '10:15am'}
  - title: Lunch
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '10:30am', to: '2:00pm'}
      - {days: [Sa, Su], from: '11:00am', to: '1:30pm'}
  - title: Dinner
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Sa, Su], from: '4:30pm', to: '7:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

hey this might actually work

**Comment by hawkrives** [comment]
```js
let res = ''
for (let line of jsYaml.safeDump(data, {flowLevel: 4}).split(\'n')) {
 if (['schedule:', 'breakSchedule:'].includes(line)) {
   res += `\n\n${line}`
 }
 else if (line.startsWith('  - title:') && prev !== 'schedule:') {
   res += `\n\n${line}`
 }
 else {
   res += `\n${line}`
 }
 prev = line
}
console.log(res)
```

```yaml
name: Stav Hall
image: stav
category: Food

schedule:
  - title: Breakfast
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Sa], from: '7:00am', to: '9:45am'}
      - {days: [Su], from: '8:30am', to: '10:15am'}

  - title: Lunch
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '10:30am', to: '2:00pm'}
      - {days: [Sa, Su], from: '11:00am', to: '1:30pm'}

  - title: Dinner
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Sa, Su], from: '4:30pm', to: '7:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
