### ISSUE TITLE
Building hours update for Tostrud Climbing Wall

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1748]
## Before:

```yaml
name: Tostrud Climbing Wall
category: Gym

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '6:30am', to: '10:45pm'}
      - {days: [Fr], from: '6:30am', to: '8:45pm'}
      - {days: [Sa], from: '9:00am', to: '8:45pm'}
      - {days: [Su], from: '12:00pm', to: '10:45pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Th], from: '4:00pm', to: '6:00pm'}]
```

## After:

```yaml
name: Tostrud Climbing Wall
category: Gym

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '6:30am', to: '10:45pm'}
      - {days: [Fr], from: '6:30am', to: '8:45pm'}
      - {days: [Sa], from: '9:00am', to: '8:45pm'}
      - {days: [Su], from: '12:00pm', to: '10:45pm'}
    notes: Sun - Fri 4-9 PM.    Sat - 1-5 PM

  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Su], from: '4:00pm', to: '9:00pm'}
      - {days: [Sa], from: '1:00pm', to: '5:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Th], from: '4:00pm', to: '6:00pm'}]
```
