### ISSUE TITLE
Building hours update for Skoglund

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1750]
## Before:

```yaml
name: Skoglund
image: skoglund
category: Gym

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '6:30am', to: '10:45pm'}
      - {days: [Fr], from: '6:30am', to: '8:45pm'}
      - {days: [Sa], from: '9:00am', to: '8:45pm'}
      - {days: [Su], from: '12:00pm', to: '10:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Tu, We, Th], from: '8:00am', to: '7:00pm'}, {days: [Fr], from: '8:00am', to: '2:00pm'}]
```

## After:

```yaml
name: Skoglund
image: skoglund
category: Gym

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '6:30am', to: '10:30pm'}
      - {days: [Fr], from: '6:30am', to: '8:45pm'}
      - {days: [Sa], from: '9:00am', to: '8:45pm'}
      - {days: [Su], from: '12:00pm', to: '10:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Tu, We, Th], from: '8:00am', to: '7:00pm'}, {days: [Fr], from: '8:00am', to: '2:00pm'}]
```
