### ISSUE TITLE
Building hours update for Holland Hall

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1893]
## Before:

```yaml
name: Holland Hall
category: Academia

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '7:00am', to: '10:00pm'}
      - {days: [Fr], from: '7:00am', to: '6:00pm'}
      - {days: [Su], from: '12:00pm', to: '10:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

## After:

```yaml
name: Holland Hall
category: Academia

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '7:00am', to: '10:00pm'}
      - {days: [Fr], from: '7:00am', to: '6:00pm'}
      - {days: [Sa], from: '8:00am', to: '6:00pm'}
      - {days: [Su], from: '8:00am', to: '10:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
