### ISSUE TITLE
Building hours update for The Cage

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1898]
> The cage late night closes at 10 this year, not 11 :)

## Before:

```yaml
name: The Cage
image: cage
category: Food

schedule:
  - title: Kitchen
    notes: The kitchen stops cooking at 8 p.m.
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '7:30am', to: '8:00pm'}
      - {days: [Sa, Su], from: '9:00am', to: '8:00pm'}

  - title: Late Night
    hours:
      - {days: [Mo, Tu, We, Th], from: '8:00pm', to: '11:00pm'}
      - {days: [Su], from: '8:00pm', to: '11:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Kitchen
      hours: [{days: [Mo, Tu, We, Th], from: '7:30am', to: '3:00pm'}, {days: [Fr], from: '7:30am', to: '1:00pm'}]
```

## After:

```yaml
name: The Cage
image: cage
category: Food

schedule:
  - title: Kitchen
    notes: The kitchen stops cooking at 8 p.m.
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '7:30am', to: '8:00pm'}
      - {days: [Sa, Su], from: '9:00am', to: '8:00pm'}

  - title: Late Night
    hours:
      - {days: [Mo, Tu, We, Th], from: '8:00pm', to: '10:00pm'}
      - {days: [Su], from: '8:00pm', to: '10:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Kitchen
      hours: [{days: [Mo, Tu, We, Th], from: '7:30am', to: '3:00pm'}, {days: [Fr], from: '7:30am', to: '1:00pm'}]
```
