### ISSUE TITLE
Building hours update for STORP

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2164]
As noted in an email. 

## Before:

```yaml
name: STORP
subtitle: St. Olaf Outdoor Recreation Program
category: Gym

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Th, Fr], from: '4:00pm', to: '6:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Th], from: '4:00pm', to: '6:00pm'}]
```

## After:

```yaml
name: STORP
subtitle: St. Olaf Outdoor Recreation Program
category: Gym

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Fr], from: '4:00pm', to: '6:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Th], from: '4:00pm', to: '6:00pm'}]
```
