### ISSUE TITLE
Building hours update for Rølvaag Library

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2426]
## Before:

```yaml
name: Rølvaag Library
image: rolvaag-library
category: Libraries

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '8:00am', to: '12:00am'}
      - {days: [Fr], from: '8:00am', to: '6:00pm'}
      - {days: [Sa], from: '9:00am', to: '6:00pm'}
      - {days: [Su], from: '12:00pm', to: '12:00am'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Tu, We, Th], from: '7:30am', to: '5:00pm'}, {days: [Fr], from: '7:30am', to: '1:00pm'}]
```

## After:

```yaml
name: Rølvaag Library
image: rolvaag-library
category: Libraries

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th], from: '7:45am', to: '2:00am'}
      - {days: [Fr], from: '7:45am', to: '9:00pm'}
      - {days: [Sa], from: '9:00am', to: '9:00pm'}
      - {days: [Su], from: '12:00pm', to: '2:00am'}
    notes: Odd hours for breaks; check schedule for details

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Tu, We, Th], from: '7:30am', to: '5:00pm'}, {days: [Fr], from: '7:30am', to: '1:00pm'}]
```
