### ISSUE TITLE
Building hours update for Registrar

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2615]
## Before:

```yaml
name: Registrar
category: Offices

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '8:00am', to: '4:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Tu, We, Th], from: '7:30am', to: '4:30pm'}, {days: [Fr], from: '7:30am', to: '12:00pm'}]
```

## After:

```yaml
name: Registrar
category: Offices

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '8:00am', to: '4:30pm'}
    closedForChapelTime: true

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer:
    - title: Hours
      hours: [{days: [Mo, Tu, We, Th], from: '7:30am', to: '4:30pm'}, {days: [Fr], from: '7:30am', to: '12:00pm'}]
```
