### ISSUE TITLE
[needs verification] Building hours update for RNS

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3097]
From an email; we should verify this. 

## Before:

```yaml
name: RNS
subtitle: Regents Hall of Natural Sciences
category: Academia
image: regents-hall

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Sa, Su], from: '7:00am', to: '10:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

## After:

```yaml
name: RNS
subtitle: Regents Hall of Natural Sciences
category: Academia
image: regents-hall

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr, Sa, Su], from: '7:00am', to: '12:00am'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
