### ISSUE TITLE
Building hours update for Center for Arts and Dance

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3148]
## Before:

```yaml
name: Center for Arts and Dance
category: Academia
image: center-for-arts-and-dance

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '7:00am', to: '5:00pm'}
      - {days: [Sa], from: '8:00am', to: '7:00pm'}
      - {days: [Su], from: '10:00am', to: '7:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

## After:

```yaml
name: Center for Arts and Dance
category: Academia
image: center-for-arts-and-dance

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '7:00am', to: '10:30pm'}
      - {days: [Sa], from: '8:00am', to: '7:00pm'}
      - {days: [Su], from: '10:00am', to: '7:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
