### ISSUE TITLE
[github] Investigate an "auto-merge" github app

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3242]
https://github.com/SvanBoxel/auto-merge

It has an option to auto-merge approved and green PRs with the `auto-merge` label -

```yaml
# .github/auto-merge-settings.yml
merge_method: 'merge'
strategy: 'label'
```

I think it'd be really nice 😸 

Thoughts?
