### ISSUE TITLE
Building hours update for Post Office

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3788]
this looks correct to me

## Before:

```yaml
name: Post Office
image: post-office
category: Mail and Packages

schedule:
  - title: Hours
    closedForChapelTime: true
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '8:00am', to: '5:00pm'}
      - {days: [Sa], from: '10:00am', to: '1:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

## After:

```yaml
name: Post Office
image: post-office
category: Mail and Packages

schedule:
  - title: Hours
    closedForChapelTime: true
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '8:00am', to: '3:00pm'}
      - {days: [Sa], from: '10:00am', to: '1:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
