### ISSUE TITLE
Building hours update for Skoglund Pool

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#4464]
## Before:

```yaml
name: Skoglund Pool
category: Gym

schedule:
  - title: Lap Swim
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '12:00pm', to: '2:00pm'}

  - title: Open Swim
    hours:
      - {days: [Mo, We, Fr], from: '6:30pm', to: '8:30pm'}
      - {days: [Tu, Th], from: '6:30pm', to: '10:00pm'}
      - {days: [Sa, Su], from: '2:00pm', to: '4:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

## After:

```yaml
name: Skoglund Pool
category: Gym

schedule:
  - title: Lap Swim
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: '1:00pm', to: '2:00pm'}
      - {days: [Tu, We, Th], from: '12:00pm', to: '1:00pm'}

  - title: Open Swim
    hours:
      - {days: [Mo, We, Fr], from: '6:30pm', to: '8:30pm'}
      - {days: [Tu, Th], from: '6:00pm', to: '8:00pm'}
      - {days: [Sa, Su], from: '2:00pm', to: '4:30pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
