### ISSUE TITLE
Add phone number validation pattern

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#515]
Split from https://github.com/StoDevX/AAO-React-Native/pull/512#issuecomment-271098611: "If the current format is just a string of numbers (e.g., 9185789388?), we could add a piece to the `definitions` in defs.yaml:"

```yaml
phone:
  type: string
  pattern: ^\d{9}$
```
