### ISSUE TITLE
Add Offices to hours view

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#544]
Probably should, since we've got literally every room around it listed.

What category should it go in?

```yaml
name: Center for Multicultural Engagement
abbreviation: CMIE
category: Offices

schedule:
  - title: Hours
    hours: 
      - {days: [Mo, Tu, We, Th], from: '8:00am', to: '8:00pm'}
      - {days: [Fr], from: '8:00am', to: '5:00pm'}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

* [x] CMIE
* [x] OSA
* [ ] Gender & Sexuality Center
* [x] Conferences, Camps and Events
* [ ] Telecom
* [x] Parking
* [x] Admissions
* [x] Piper Center
* [ ] Bon App office
* [x] Business
* [x] Financial Aid
* [x] SARN
* [x] Pastor's Office
* [x] IT Helpdesk
* [x] Registrar
