### ISSUE TITLE
Building Hours are incorrectly marked as "open"

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#622]
I've added a test to the app:

```
  knows that "days: Fr, to: 2am" really closes on Saturday morning
    ✕ is closed on Friday morning (11ms)
    ✓ is open on Saturday morning (5ms)
  knows that "days: [Fr, Sa], to: 2am" really closes is open Sat@2am, Sun@2am
    ✕ is closed on Friday morning (4ms)
    ✓ is open on Saturday morning (9ms)
    ✓ is open on Sunday morning (4ms)
    ✕ is closed on Monday morning (4ms)
```

I have a branch that improves(?) the situation:

```
knows that "days: Fr, to: 2am" really closes on Saturday morning
    ✓ is closed on Friday morning (11ms)
    ✓ is open on Saturday morning (5ms)
  knows that "days: [Fr, Sa], to: 2am" really closes is open Sat@2am, Sun@2am
    ✓ is closed on Friday morning (4ms)
    ✕ is open on Saturday morning (9ms)
    ✕ is open on Sunday morning (4ms)
    ✓ is closed on Monday morning (4ms)
```

but, ah, it's not ready for PR yet. I think we might need to rethink how we handle these cases again…

**Comment by hawkrives** [comment]
I've enclosed below some thoughts around this bug that have been languishing in my chat archives for many moons.

---

#### Hawken Rives, [Jan 25, 2017, 10:19 AM]:
I am reasonably sure that we'll need to observe the entire list of schedules for a building in order to fix this, instead of the current one-schedule-at-a-time method…

… of course, then you still have the issue of between weeks, so I'd prefer to not have to move up a level…

so, because each schedule is parsed individually, and because the current approach only looks at one schedule at a time, and therefore switches based on the day

Let's take `{days: ['Fr', 'Sa'], from: '9:00pm', to: '2:00am'}`

I don't think there's any way for the current approach to show the correct "open on sunday until 2am" status.

because, come sunday, that schedule's not even going to be processed

#### Drew Volz, [Jan 25, 2017, 12:36 PM]:
you are correct... the schedule has changed at that point.

it's almost as if we need to check the previous day in addition to the current day

wouldn't that be the correct approach? check the end time on (day - 1) on (day) to conclude whether or not (day - 1) is still operating?

#### Hawken Rives, [Jan 25, 2017, 12:38 PM]:
so it's not terribly simple to find the "previous" schedule

it's not inconcievable that we'd have a schedule like this

```yaml
- {days: [Mo, Tu, We, Th, Fr], from: '10:00am', to: '5:00pm'}
- {days: [Fr], from: '7:00pm', to: '9:00pm'}
```

where a secondary schedule only applies to a subset / superset of the first found one

#### Drew Volz, [Jan 25, 2017, 5:32 PM]:
For data parsing's sake, would it make sense to have some sort of unwrapper to flatten the schedule into one array of days? 

It wouldn't matter if there are multiple schedules or not as it would need to satisfy a simple truthiness test

Does that make sense out loud? In my head it makes sense.

#### Hawken Rives, [Jan 25, 2017, 5:33 PM]:
`parseHours` is also used in `getStatusOfBuildingAtMoment`, which is what returns the formatted "closes in x minutes" stuff

so it's not always a simple boolean check

i mean, one of the uses is, but we've got three uses

1. formatting the times for the list of times (h:mma / midnight)
2. formatting "opens in ten minutes"
3. boolean "is the building open right now"

#### Drew Volz, [Jan 25, 2017, 5:35 PM]:
Okay. Would my suggestion work though...

#### Hawken Rives, [Jan 25, 2017, 5:36 PM]:
gimme a sec to play… so, like,

```yaml
# from
- {days: [Mo, Tu, We, Th], from: '10:00am', to: '5:00pm'}
- {days: [Mo, Tu, We, Th], from: '7:00pm', to: '9:00pm'}
- {days: [Fr], from: '10:00am', to: '5:00pm'}
- {days: [Su], from: '1:30pm', to: '5:00pm'}
- {days: [Su], from: '7:00pm', to: '9:00pm'}

# to
Mo: [{from: '10:00am', to: '5:00pm'}, {from: '7:00pm', to: '9:00pm'}]
Tu: [{from: '10:00am', to: '5:00pm'}, {from: '7:00pm', to: '9:00pm'}]
We: [{from: '10:00am', to: '5:00pm'}, {from: '7:00pm', to: '9:00pm'}]
Th: [{from: '10:00am', to: '5:00pm'}, {from: '7:00pm', to: '9:00pm'}]
Fr: [{from: '10:00am', to: '5:00pm'}]
Sa: []
Su: [{from: '10:00am', to: '5:00pm'}, {from: '7:00pm', to: '9:00pm'}]
```

(a map of days to array of times on that day)?

#### Drew Volz, [Jan 25, 2017, 5:38 PM]:
Just internally. That way you can query the current day to the previous day

And then evaluate the times underneath the map (and handling if there are multiples)

#### Drew Volz, [Jan 25, 2017, 5:39 PM]:
> (a map of days to array of times on that day)?
Yes! Precisely. Is that hard?

#### Hawken Rives, [Jan 25, 2017, 5:39 PM]:
hang on, gonna reformat the pause times to look

#### Hawken Rives, [Jan 25, 2017, 5:43 PM]:
```yaml
- title: Daylight
  notes: The late night menu starts at 9 p.m.
  hours:
    - {days: [Mo], from: '10:30am', to: '12:00am'}
    - {days: [Tu], from: '11:30am', to: '12:00am'}
    - {days: [We], from: '10:30am', to: '12:00am'}
    - {days: [Th], from: '11:30am', to: '12:00am'}
    - {days: [Fr], from: '10:30am', to: '9:00pm'}
    - {days: [Sa], from: '11:30am', to: '9:00pm'}
    - {days: [Su], from: '11:30am', to: '12:00am'}

- title: Late Night
  hours:
    - {days: [Fr, Sa], from: '9:00pm', to: '2:00am'}

# becomes

Mo: [{from: '10:30am', to: '12:00am'}]
Tu: [{from: '11:30am', to: '12:00am'}]
We: [{from: '10:30am', to: '12:00am'}]
Th: [{from: '11:30am', to: '12:00am'}]
Fr: [{from: '10:30am', to: '9:00pm'}, {from: '9:00pm', to: '2:00am'}]
Sa: [{from: '11:30am', to: '9:00pm'}, {from: '9:00pm', to: '2:00am'}]
Su: [{from: '11:30am', to: '12:00am'}]
```

#### Hawken Rives, [Jan 25, 2017, 5:43 PM]:
question is, is there any reason we'd need to know which set of schedules the time is from?

#### Drew Volz, [Jan 25, 2017, 5:44 PM]:
Which set... well... 😐

If the map maps them... no?

#### Hawken Rives, [Jan 25, 2017, 5:44 PM]:
I'm trying to figure the three uses in my head

#### Drew Volz, [Jan 25, 2017, 5:45 PM]:
Keep in mind this should be separate, IMHO, not replacing.

Because you've got multi-purpose code.

#### Hawken Rives, [Jan 25, 2017, 5:45 PM]:
① can be separate. ② and ③ need to share the parsing though? since we don't want it to say "closing in x minutes" incorrectly?

… actually, ② might be easier with this… because you'd be able to check if the building has another schedule and not close if they start/end at the same time, like the late night stuff.

#### Drew Volz, [Jan 25, 2017, 5:47 PM]:
Yes! Eliminate accidental closing text if we're simply continuing without delay.
