### ISSUE TITLE
Building hours update for Bookstore

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#7102]
## Before:

```yaml
name: Bookstore
image: bookstore
category: Supplies and Books

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: 8:00am, to: 5:00pm}
      - {days: [Sa], from: 10:00am, to: 4:00pm}
      - {days: [Su], from: 10:00am, to: 2:00pm}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```

## After:

```yaml
name: Bookstore
image: bookstore
category: Supplies and Books

schedule:
  - title: Hours
    hours:
      - {days: [Mo, Tu, We, Th, Fr], from: 8:00am, to: 5:00pm}
      - {days: [Sa], from: 10:00am, to: 3:00pm}

breakSchedule:
  fall: []
  thanksgiving: []
  winter: []
  interim: []
  spring: []
  easter: []
  summer: []
```
